GEMINI_API_KEY = "AIzaSyC_8ClX3ZFanOi0O50jZulNKwspLm-Rxrs"
SUPABASE_URL = "https://exlgpawyivedpyfelehx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4bGdwYXd5aXZlZHB5ZmVsZWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzMwODQsImV4cCI6MjA3MzM0OTA4NH0.UaUutGAd8XMRCv3NwYYCgNyNWir9BAXAKhAxh1v5nPw"